//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer()
        {
            this.ScholarAnswer = new HashSet<ScholarAnswer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StatementId { get; set; }
        public string Text { get; set; }
        public bool IsDefault { get; set; }
        public bool IsCustom { get; set; }
        public string CustomPrompt { get; set; }
    
        public virtual Statement Statement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarAnswer> ScholarAnswer { get; set; }
    }
}
