//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSurvey.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyModelEntities : DbContext
    {
        public SurveyModelEntities()
            : base("name=SurveyModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Scholar> Scholar { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<Statement> Statement { get; set; }
        public virtual DbSet<ScholarAnswer> ScholarAnswer { get; set; }
    }
}
